config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :authors
  get "react", to: "react#index", format: false
  get "react/*path", to: "react#index", format: false
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_path, status: :see_other, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.expect(author: [ :name, :email ])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:author).all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body, :author_id ])
    end
end

app/controllers/react_controller.rb
class ReactController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= author.email %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<% content_for :title, "Editing author" %>

<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Authors" %>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<% content_for :title, "New author" %>

<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Hotwire React Compare" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<nav class="bg-gray-800 text-white p-2 flex justify-center gap-10 items-center">
  <%= link_to "Hotwire", root_path, class: "text-red-500 font-extrabold" %>
  <%= link_to "React", "/react", class: "text-blue-500 font-extralight", data: { turbo: false } %>
</nav>
<div class="container mx-auto my-16">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/react.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hotwire React Compare" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "react", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :title, class: "block text-sm" %>
    <%= form.text_field :title, class: "p-1 border rounded" %>
  </div>

  <div class="mb-2">
    <%= form.label :body, class: "block text-sm" %>
    <%= form.textarea :body, class: "p-1 border rounded" %>
  </div>

  <div class="mb-2">
    <%= form.label :author_id, class: "block text-sm"%>
    <%= form.select :author_id, Author.all.map { [_1.name, _1.id] }, {}, { class: "p-1 border rounded appearance-none pr-8" } %>
  </div>

  <div>
    <%= form.submit class: "p-2 rounded bg-orange-600 text-white cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Author Name:</strong>
    <%= post.author.name %>
  </p>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1 class="text-5xl mb-16">Posts</h1>

<%= link_to "New post", new_post_path, class: "p-2 rounded bg-orange-600 text-white" %>
<script>
  // Typically, this would be written using Stimulus.

  function openModal() {
    document.getElementById("modal").showModal();
  }

  function closeModal() {
    document.getElementById("modal").close();
  }
</script>

<div id="posts" class="mt-8">
  <% @posts.each do |post| %>
    <div class="mb-4">
      <%= render post %>
      <p>
        <%= link_to "Show this post", post, class: "inline-block p-1 rounded border border-orange-600 text-orange-600" %>
      </p>
      <p class="mt-4">
        <%= link_to "Show in modal", post,
                    class: "inline-block p-1 rounded border border-orange-600 text-orange-600",
                    data: { turbo_frame: "modal-frame" },
                    onclick: "openModal()" %>
      </p>
    </div>
  <% end %>
</div>

<dialog id="modal" class="relative min-w-96 min-h-96 p-4 rounded-xl">
  <button onclick="closeModal()" class="absolute right-4 top-4 bg-white rounded-full text-3xl bold">x</button>
  <div class="mt-8">
  <turbo-frame id="modal-frame"></turbo-frame>
  </div>
</dialog>

app/views/posts/index_bak.html.erb
<table class="border">
  <thead>
    <th class="border p-1">Title</th>
    <th class="border p-1">Body</th>
    <th class="border p-1">CreatedAt</th>
    <th class="border p-1">AuthorName</th>
    <th class="border p-1">AuthorEmail</th>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td class="border p-1"><%= post.title %></td>
      <td class="border p-1"><%= post.body %></td>
      <td class="border p-1"><%= l post.created_at, format: :short %></td>
      <td class="border p-1"><%= post.author.name %></td>
      <td class="border p-1"><%= post.author.email %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1 class="text-5xl mb-8">New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "p-1 rounded border border-orange-600 text-orange-600" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag "modal-frame" do %>
  <%= render @post %>
<% end %>

<div class="mt-8">
  <%= link_to "Back to posts", posts_path, class: "p-1 rounded border border-orange-600 text-orange-600" %>
</div>

app/views/react/index.html.erb
<% provide :head, javascript_include_tag("react", type: "module") %>

<div id="root"></div>